# Web容器服务配置
server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
    remoteip:
      protocol-header: x-forwarded-proto
      port-header: X-Forwarded-Port
      remote-ip-header: x-forwarded-for

# Spring配置
spring:
  # 应用配置
  application:
    name: single-admin

  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/single?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  # Redis配置
  redis:
    host: localhost
    port: 6379

  # 定时任务配置
  task:
    execution:
      thread-name-prefix: Job-Thread-

  servlet:
    # 文件上传最大10M
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# MyBatis Plus 配置
mybatis-plus:
  # 扫描 xml 路径
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    # 全局配置
    db-config:
      # 逻辑删除字段
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  config: classpath:log4j2-spring.xml

# Swagger 配置
swagger:
  title: AgeFades 单体后台API
  description: 当前环境:本地开发
  version: 1.0

sentry:
  dsn: http://e8bfab3cdfed4b1c9b4abafbd029b74c@sentry.agefades.com/5
  environment: dev
  server-name: single-admin
  exception-resolver-order: 2147483647
  debug: true